## Stage Development
FROM node:20-alpine AS development

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

CMD ["npm", "run", "dev"]

## Stage Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

RUN npm run build

## Stage Deploy
FROM node:20-alpine AS deploy

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/build ./build

CMD ["npm", "run", "start"]
