services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: development
    volumes:
      - .:/workspace:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5000/api
    user: root

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace:cached
      - backend_node_modules:/workspace/backend/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/recipe-book
    user: root
    command: ["npm", "run", "dev"]

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recipe-book
  prism-mock:
    image: stoplight/prism:4
    ports:
      - "4010:4010"
    volumes:
      - ./doc/openapi.yaml:/usr/src/api.yaml
    command: mock -h 0.0.0.0 /usr/src/api.yaml --errors
volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules:
