services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: development
    volumes:
      - .:/workspace:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://backend:5000/api
    user: root

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace:cached
      - backend_node_modules:/workspace/backend/node_modules
    depends_on:
      - database
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://database:27017/recipe-book
    user: root

  database:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: recipe-book

volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules:
