version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5000/api

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: development
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/recipe-book

  database:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recipe-book

volumes:
  mongodb_data:
