services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: development
    volumes:
      - .:/workspace:cached
      - /workspace/frontend/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5000/api
    user: root

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace:cached
      - /workspace/backend/node_modules
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/recipe-book
    user: root

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recipe-book

volumes:
  mongodb_data:
