## Stage Development
FROM node:20-alpine AS development

WORKDIR /app

COPY backend/package.json ./
RUN npm install

COPY backend/ .

CMD ["npm", "run", "dev"]

## Stage Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY backend/package.json ./
RUN npm install

COPY backend/ .

## Stage Deploy
FROM node:20-alpine AS deploy

WORKDIR /app

COPY backend/package.json ./
RUN npm install --omit=dev

COPY backend/ .

CMD ["npm", "run", "start"]
